### ISSUE TITLE
The avatar image is not displayed when used with Electron.

### ISSUE THREAD

**Issue by logue** [JiriChara/vue-gravatar#17]
The output img tag does not contain https in its src, so the image will not be displayed when used with [Electron](https://www.electronjs.org/).

```
<img src="//www.gravatar.com/avatar/55cd40fddaa006a743cbf7532f021ee1?s=128&amp;d=retro&amp;r=g" alt="Avatar">
```

**Comment by JiriChara** [comment]
Fixed in https://github.com/JiriChara/vue-gravatar/releases/tag/v1.4.1
