### ISSUE TITLE
Component doesn't work with Safari 11

### ISSUE THREAD

**Issue by roquie** [JiriChara/vue-gravatar#2]
Hi!

Example page doesn't work in Apple Safari browser. Component loaded the image,  but can't to paste him to template. Console is empty.

Safari Version 11.0 (12604.1.38.1.7)

**Comment by JiriChara** [comment]
Hey @roquie,

sorry for late reply for some reason, I didn't get any notification.

I am not quite sure if I understand your problem. Do you think you can provide an actual code or a screencast?

**Comment by roquie** [comment]
Hi!

Sorry, is not a bug, I forgot the turn off Ghostery plugin before create issue. Have a nice day :)

**Comment by JiriChara** [comment]
perfect :sweat_smile:
